# Generated by Django 4.0 on 2021-12-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_ebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='booklist',
            field=models.ManyToManyField(to='audio_ebook.Book'),
        ),
    ]
