# Generated by Django 4.0 on 2021-12-20 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio_ebook', '0003_book_type_of_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default=1000, max_length=800),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AudiobookDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_id', models.IntegerField()),
                ('start_time', models.CharField(max_length=8)),
                ('end_time', models.CharField(max_length=8)),
                ('ISBN', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='audio_ebook.book')),
            ],
        ),
    ]
