# Generated by Django 4.0 on 2021-12-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_ebook', '0004_book_description_audiobookdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='source',
            field=models.CharField(default=1000, max_length=800),
            preserve_default=False,
        ),
    ]
