# Generated by Django 4.0 on 2021-12-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_ebook', '0005_book_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='source',
            field=models.CharField(default='', max_length=800),
        ),
    ]
